#!/bin/sh
case "$1" in
    "--inc") xbacklight -inc ${2:-5};;
    "--dec") xbacklight -dec ${2:-5};;
    "--set") xbacklight -set "$2";;
esac
blp="$(xbacklight -get)"
#dunstify "$(echo -n 💡$(percentbar.sh $blp) )" -r 212 -u LOW -t 1250
# 212 is arbitrary (b=2 l=12)
dunstify "$(echo "💡$(percentbar $blp)" )" -r 212 -u LOW -t 1250
