#!/usr/bin/env sh
# this doesnt have a huge reason to exist but it is prolly faster than bgrep and does filter on executables
pat="$1" && shift
find $(printenv PATH | tr ':' ' ') -maxdepth 1 -type f -executable -iregex ".*/[^/]*$pat[^/]*" "$@" 2> /dev/null
