#!/bin/sh
# exit if blockbutton exists (after running command)
case "$BLOCK_BUTTON" in
    #1) exec xclock;;
    2) exec edit "$0";;
    3) exec ${TERMINAL:-st} -e sh -c 'cal; read -p "Press [Enter] to exit.." in';;
    '') false;;
esac && exit

clocks="🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛"
hour=$(date "+%-I")
echo -n $(echo "$clocks" | cut -c $(( ($hour-1)*4+1 ))-$(( $hour*4 )) ) $(date "+%b %d, %r")
