#!/bin/sh
# exit if blockbutton exists and isnt the middle mouse (if it is then open this file in editor), if left click open xclock otherwise quit
[ -n "$BLOCK_BUTTON" ] && { [ "$BLOCK_BUTTON" -eq 2 ] && { "$TERMINAL" -e "$EDITOR" "$0"; exit; } || [ "$BLOCK_BUTTON" -eq 1 ] && { xclock; exit; } || exit; }
clocks="🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛"
hour=$(date "+%-I")
echo -n $(echo "$clocks" | cut -c $(( ($hour-1)*4+1 ))-$(( $hour*4 )) ) $(date "+%b %d, %r")
