#!/bin/sh
set -e

if [ -n "$DISPLAY" ] && ! ps o command= $(ps o ppid= $(pgrep -s $(ps o session= $$))) | grep -q '\--embed'; then
    export FIFO_UEBERZUG="$(mktemp -ut lf-ueberzug.XXXXXXXXXX)"
    mkfifo "$FIFO_UEBERZUG"

    cleanup() {
        exec 3>&-
        rm "$FIFO_UEBERZUG"
    }

    ueberzug layer -s <"$FIFO_UEBERZUG" &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup EXIT

    if ! [ -d "$HOME/.cache/lf" ]; then
        mkdir -p "$HOME/.cache/lf"
    fi

    lf "$@" 3>&-
else
    exec lf "$@"
fi
