#!/bin/sh
# this script just loops, checks if its within a minute till the screensaver turns on, and if it is it moves the mouse to a random location
# this is dumb, for 1 option itd be better to just get the flag from the basic shell way
eval $(echo 'flags: c,choose; parameters: choose,c;' | clparser "$@")
# NOTE for the record i think kill $$ is super disgusting but it works and i dont want to do something more complicated
[ "$c" = 1 ] && tl="$(printf '30m\n1h\n1.5h' | dmenu)" || { [ -n "$c" ] && tl="$c"; }
[ -n "$tl" ] && echo $tl && sleep "$tl" && kill $$ &

size=$(xrandr | grep -o '[0-9]\+x[0-9]\++' | tr 'x+' ' ')
while true; do [ $(xssstate -t) -lt 60000 ] && swarp $(shuf -i 1-$(echo $size | cut -d ' ' -f 1) -n 1) $(shuf -i 1-$(echo $size | cut -d ' ' -f 2) -n 1) && sleep  1 || sleep 1m; done
