#!/bin/sh
# print out the no bell symbol if paused and if not print the bell and num notifications of > 0, otherwise dont print
# this script is dunst only in case that isnt clear
printstuffs () {
    [ "$(dunstctl is-paused)" = 'true' ] && printf "%s" '🔕' || {
        num="$(dunstctl count | awk '/Waiting/ { print $2; exit }')"
        [ "$num" -gt 0 ] && printf "%s %d" '🔔' "$num"
    };
}
case "$BLOCK_BUTTON" in
    2) edit "$0" ;;
    3) dunstctl set-paused toggle ;;
    '') printstuffs ;;
esac
