#!/bin/sh
# TODO maybe do input the normal way since we only have q at the moment
eval $(echo 'flags: q,quiet;' | clparser -- "$@")
trashdir=${XDG_DATA_HOME:-$HOME/.local/share}/Trash/rmt
resfile=$trashdir/$(ls -r $trashdir | fzf +s +m -i --query=$@) || exit
resdir=$(basename $resfile | sed 's/.*_//; s|%|/|g; s|-.*||')
##unzip -v $resfile
##tar -jtvf $resfile
#tar -I lbzip2 -tvf $resfile
# TODO make it so i can pick the files to restore with fzf rather than just doing all
# the quiet is for unzip, tar is quiet and doesnt have q, also we print everything out above so maybe just dont do that for quiet
# TODO i have a small minor problem that my oldest trash is zip and then i switched to bz2 but whatever (itd be nice if they said their filetype to make that clear but whatever)
$q && quiet= || quiet='-v'
#unzip -X $quiet $resfile -d $resdir
#tar -xjf $resfile -C $resdir
tar -I lbzip2 $quiet -xf $resfile -C $resdir
